# Generated by Django 5.2.8 on 2026-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.BigIntegerField(blank=True, default=1, editable=False, null=True, unique=True),
        ),
    ]
