# Generated by Django 5.2.8 on 2025-11-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='eng_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='doc_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
