# Generated by Django 5.2.8 on 2026-01-19 08:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_church_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEXT', 'Texte'), ('AUDIO', 'Audio')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text_content', models.TextField(blank=True, help_text='Le contenu texte du témoignage', null=True)),
                ('audio_url', models.URLField(blank=True, help_text="URL de l'audio du témoignage", max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Durée en secondes pour les audios', null=True)),
                ('status', models.CharField(choices=[('PENDING', "En attente d'approbation"), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], db_index=True, default='PENDING', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text="Visible publiquement dans l'église")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet si applicable', null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_testimonies', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to='api.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', '-created_at'], name='api_testimo_church__8771be_idx'), models.Index(fields=['user'], name='api_testimo_user_id_255e12_idx'), models.Index(fields=['church', 'status'], name='api_testimo_church__2c103e_idx'), models.Index(fields=['church', 'is_public', '-created_at'], name='api_testimo_church__3aa868_idx')],
            },
        ),
    ]
