# Generated by Django 5.2.8 on 2025-11-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_commission_eng_name_alter_church_doc_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('denied_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denied_members', to='api.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denied_in_churches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('church', 'user')},
            },
        ),
    ]
