# Generated by Django 5.2.8 on 2025-11-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_deny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
    ]
