# Generated by Django 5.2.8 on 2026-01-19 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testimony'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchCollaboration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Titre de la collaboration', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la collaboration', null=True)),
                ('collaboration_type', models.CharField(choices=[('PARTNERSHIP', 'Partenariat'), ('EVENT', 'Événement'), ('RESOURCE_SHARING', 'Partage de ressources'), ('MINISTRY', 'Ministère conjoint'), ('OTHER', 'Autre')], db_index=True, default='PARTNERSHIP', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée'), ('ENDED', 'Terminée')], db_index=True, default='PENDING', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Date de début de la collaboration', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date de fin prévue', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Raison du rejet', null=True)),
                ('goals', models.TextField(blank=True, help_text='Objectifs de la collaboration', null=True)),
                ('expected_outcome', models.TextField(blank=True, help_text='Résultat attendu', null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_collaborations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaborations', to=settings.AUTH_USER_MODEL)),
                ('initiator_church', models.ForeignKey(help_text="L'église qui initie la collaboration", on_delete=django.db.models.deletion.CASCADE, related_name='initiated_collaborations', to='api.church')),
                ('target_church', models.ForeignKey(help_text="L'église avec laquelle collaborer", on_delete=django.db.models.deletion.CASCADE, related_name='received_collaborations', to='api.church')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['initiator_church', 'status'], name='api_churchc_initiat_cfd3a6_idx'), models.Index(fields=['target_church', 'status'], name='api_churchc_target__9516fb_idx'), models.Index(fields=['collaboration_type'], name='api_churchc_collabo_504ff3_idx'), models.Index(fields=['-created_at'], name='api_churchc_created_18c76c_idx')],
                'unique_together': {('initiator_church', 'target_church')},
            },
        ),
        migrations.CreateModel(
            name='TestimonyLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['testimony'], name='api_testimo_testimo_cb786e_idx'), models.Index(fields=['user'], name='api_testimo_user_id_519fca_idx')],
                'unique_together': {('testimony', 'user')},
            },
        ),
    ]
