# Generated by Django 5.2.8 on 2026-01-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_churchcollaboration_testimonylike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='description',
        ),
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='expected_outcome',
        ),
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='churchcollaboration',
            name='title',
        ),
        migrations.AlterField(
            model_name='churchcollaboration',
            name='collaboration_type',
            field=models.CharField(choices=[('PARTNERSHIP', 'Partenariat'), ('RESOURCE_SHARING', 'Partage de ressources'), ('FATHER', 'Ministère parternel'), ('OTHER', 'Autre')], db_index=True, default='PARTNERSHIP', max_length=50),
        ),
        migrations.AlterField(
            model_name='churchcollaboration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Rejetée')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
