# Generated by Django 5.2.8 on 2025-11-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
