# Generated by Django 5.2.8 on 2026-01-27 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_churchcollaboration_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='planned_release_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date prévue de publication (Coming Soon)', null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_type',
            field=models.CharField(choices=[('CHURCH', 'Tous les membres'), ('OWNER', 'Propriétaires'), ('PASTOR', 'Pasteurs'), ('COMMISSION', 'Commission'), ('PROGRAMME', 'Programme'), ('CUSTOM', 'Personnalisé')], default='CHURCH', max_length=20),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, help_text='Titre du programme', max_length=250)),
                ('description', models.TextField(blank=True, help_text='Description détaillée du programme')),
                ('cover_image_url', models.URLField(blank=True, help_text='Image de couverture du programme', null=True)),
                ('start_date', models.DateField(db_index=True, help_text='Date de début du programme')),
                ('end_date', models.DateField(help_text='Date de fin du programme')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], db_index=True, default='DRAFT', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Visible pour les églises collaboratrices')),
                ('duration_in_days', models.PositiveIntegerField(blank=True, help_text='Durée en jours (calculé automatiquement)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(help_text="L'église qui organise le programme", on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='api.church')),
                ('content_items', models.ManyToManyField(blank=True, help_text='Les événements, enseignements, etc. du programme', related_name='programmes', to='api.content')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='api.programme'),
        ),
        migrations.CreateModel(
            name='ProgrammeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_notified', models.BooleanField(default=False, help_text="Si l'utilisateur a été notifié de la publication")),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['content', 'is_notified'], name='api_content_content_2d02ed_idx'), models.Index(fields=['user', 'is_notified'], name='api_content_user_id_4a423d_idx')],
                'unique_together': {('content', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['church', 'status'], name='api_program_church__ac8cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['church', 'start_date'], name='api_program_church__735667_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['status', 'is_public'], name='api_program_status_01f8da_idx'),
        ),
        migrations.AddIndex(
            model_name='programme',
            index=models.Index(fields=['-created_at'], name='api_program_created_bcedea_idx'),
        ),
        migrations.AddIndex(
            model_name='programmemember',
            index=models.Index(fields=['programme', 'user'], name='api_program_program_b65278_idx'),
        ),
        migrations.AddIndex(
            model_name='programmemember',
            index=models.Index(fields=['user'], name='api_program_user_id_979a98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='programmemember',
            unique_together={('programme', 'user')},
        ),
    ]
