# Generated by Django 5.2.8 on 2026-01-30 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_content_planned_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='intro_document_url',
            field=models.URLField(blank=True, help_text='Document introductif (PDF, etc.) accessible avant le démarrage', null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='Vidéo introductive accessible avant le démarrage', null=True),
        ),
        migrations.CreateModel(
            name='ProgrammeContentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_notified', models.BooleanField(default=False, help_text="Si l'utilisateur a été notifié")),
                ('is_read', models.BooleanField(default=False, help_text="Si l'utilisateur a lu la notification")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_notifications', to='api.content')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_notifications', to='api.programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_content_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['programme', 'user', 'is_notified'], name='api_program_program_1ec503_idx'), models.Index(fields=['programme', 'is_notified'], name='api_program_program_8747d5_idx'), models.Index(fields=['user', 'is_read'], name='api_program_user_id_e8b0e5_idx')],
                'unique_together': {('programme', 'content', 'user', 'created_at')},
            },
        ),
        migrations.CreateModel(
            name='ProgrammeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_notified', models.BooleanField(default=False, help_text="Si l'utilisateur a été notifié du démarrage")),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['programme', 'is_notified'], name='api_program_program_9bc821_idx'), models.Index(fields=['user', 'is_notified'], name='api_program_user_id_8768e9_idx')],
                'unique_together': {('programme', 'user')},
            },
        ),
    ]
