# Generated by Django 5.2.8 on 2026-02-14 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_programme_intro_document_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nom du plan (ex: FREE, STARTER, PRO)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Nom d'affichage (ex: Gratuit, Démarrage, Pro)", max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Prix du plan', max_digits=12)),
                ('currency', models.CharField(default='XAF', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='Durée de validité en jours')),
                ('max_members', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de membres (null = illimité)', null=True)),
                ('max_contents', models.PositiveIntegerField(blank=True, help_text='Nombre maximum de contenus (null = illimité)', null=True)),
                ('max_storage_gb', models.PositiveIntegerField(blank=True, help_text='Stockage maximum en GB (null = illimité)', null=True)),
                ('has_chat', models.BooleanField(default=True, help_text='Accès au chat')),
                ('has_programmes', models.BooleanField(default=True, help_text='Accès aux programmes')),
                ('has_analytics', models.BooleanField(default=False, help_text='Accès aux statistiques avancées')),
                ('has_custom_branding', models.BooleanField(default=False, help_text='Personnalisation avancée')),
                ('description', models.TextField(blank=True, help_text='Description du plan')),
                ('features', models.JSONField(blank=True, default=list, help_text='Liste des fonctionnalités')),
                ('is_active', models.BooleanField(default=True, help_text="Plan disponible à l'achat")),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plans',
                'verbose_name_plural': 'Plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Plan de souscription configurable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.subscriptionplan'),
        ),
    ]
