# Generated by Django 5.2.8 on 2025-11-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_donation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='delivery_type',
            field=models.CharField(choices=[('DIGITAL', 'Numérique'), ('PHYSICAL', 'Physique')], default='DIGITAL', max_length=20),
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('DIGITAL', 'Numérique'), ('PHYSICAL', 'Physique')], default='DIGITAL', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_gateway', models.CharField(choices=[('MOMO', 'Mobile Money'), ('OM', 'Orange Money'), ('CARD', 'Carte Bancaire'), ('CASH', 'Cash'), ('OTHER', 'Autre')], default='CASH', max_length=20)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('shipped', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to='api.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
