# Generated by Django 5.2.8 on 2026-03-02 19:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_subscriptionplan_subscription_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, help_text='Plans', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.subscriptionplan'),
        ),
        migrations.CreateModel(
            name='ServiceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('maintenance', 'Mode Maintenance'), ('whatsapp', 'WhatsApp API'), ('nexaah_sms', 'Nexaah SMS'), ('freemopay', 'FreeMoPay Payment'), ('notification_preferences', 'Préférences de Notification')], db_index=True, help_text='Type de service à configurer', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='Activer/Désactiver le service')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration additionnelle (JSON)')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message affiché en mode maintenance', null=True)),
                ('whatsapp_api_token', models.CharField(blank=True, help_text="Token d'API Meta/Facebook", max_length=500, null=True)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, help_text='ID du numéro de téléphone WhatsApp', max_length=100, null=True)),
                ('whatsapp_api_version', models.CharField(blank=True, default='v18.0', help_text="Version de l'API WhatsApp", max_length=20, null=True)),
                ('whatsapp_template_name', models.CharField(blank=True, help_text='Nom du template WhatsApp', max_length=100, null=True)),
                ('whatsapp_language', models.CharField(blank=True, default='fr', help_text='Langue des messages WhatsApp', max_length=10, null=True)),
                ('nexaah_base_url', models.URLField(blank=True, help_text="URL de base de l'API Nexaah", max_length=500, null=True)),
                ('nexaah_send_endpoint', models.CharField(blank=True, default='/send', help_text='Endpoint pour envoyer les SMS', max_length=200, null=True)),
                ('nexaah_credits_endpoint', models.CharField(blank=True, default='/credits', help_text='Endpoint pour vérifier les crédits', max_length=200, null=True)),
                ('nexaah_user', models.CharField(blank=True, help_text="Nom d'utilisateur Nexaah", max_length=100, null=True)),
                ('nexaah_password', models.CharField(blank=True, help_text='Mot de passe Nexaah', max_length=200, null=True)),
                ('nexaah_sender_id', models.CharField(blank=True, default='Christlumen', help_text="ID de l'expéditeur SMS", max_length=50, null=True)),
                ('freemopay_base_url', models.URLField(blank=True, help_text="URL de base de l'API FreeMoPay", max_length=500, null=True)),
                ('freemopay_app_key', models.CharField(blank=True, help_text="Clé d'application FreeMoPay", max_length=200, null=True)),
                ('freemopay_secret_key', models.CharField(blank=True, help_text='Clé secrète FreeMoPay', max_length=200, null=True)),
                ('freemopay_callback_url', models.URLField(blank=True, help_text='URL de callback pour les paiements', max_length=500, null=True)),
                ('freemopay_init_payment_timeout', models.PositiveIntegerField(default=60, help_text="Timeout pour l'initialisation du paiement (secondes)")),
                ('freemopay_status_check_timeout', models.PositiveIntegerField(default=30, help_text='Timeout pour la vérification du statut (secondes)')),
                ('freemopay_token_timeout', models.PositiveIntegerField(default=60, help_text="Timeout pour l'obtention du token (secondes)")),
                ('freemopay_token_cache_duration', models.PositiveIntegerField(default=3600, help_text='Durée de cache du token (secondes)')),
                ('freemopay_max_retries', models.PositiveIntegerField(default=3, help_text='Nombre maximum de tentatives')),
                ('freemopay_retry_delay', models.DecimalField(decimal_places=1, default=1.0, help_text='Délai entre les tentatives (secondes)', max_digits=5)),
                ('default_notification_channel', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', help_text='Canal de notification par défaut', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de Service',
                'verbose_name_plural': 'Configurations de Services',
                'ordering': ['service_type'],
                'indexes': [models.Index(fields=['service_type'], name='api_service_service_9c4153_idx'), models.Index(fields=['is_active'], name='api_service_is_acti_dc1449_idx')],
            },
        ),
    ]
