# Generated by Django 5.2.8 on 2025-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_content_delivery_type_bookorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='withdrawed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='withdrawed',
            field=models.BooleanField(default=False),
        ),
    ]
