# Generated by Django 5.2.8 on 2026-01-09 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bookorder_withdrawed_donation_withdrawed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookorder',
            name='is_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='church',
            name='look_actuality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='allow_ticket_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='tickets_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bookorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='church',
            name='code',
            field=models.BigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='church',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners_church', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='church',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='church',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='start_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['status'], name='api_church_status_b93f00_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['country', 'city'], name='api_church_country_9a44cf_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_public'], name='api_church_is_publ_74dc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['start_at'], name='api_content_start_a_18c621_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-created_at'], name='api_content_created_d5e9ea_idx'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.content'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.bookorder'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.content'),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='api.content'),
        ),
        migrations.AddField(
            model_name='ticketreservation',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tickettype'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tickettype'),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tickettype'),
        ),
        migrations.AlterUniqueTogether(
            name='tickettype',
            unique_together={('content', 'name')},
        ),
        migrations.AddIndex(
            model_name='ticketreservation',
            index=models.Index(fields=['expires_at'], name='api_ticketr_expires_35387e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['user'], name='api_ticket_user_id_e202df_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='api_ticket_status_874e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['-issued_at'], name='api_ticket_issued__6e2936_idx'),
        ),
    ]
