# Generated by Django 5.2.8 on 2026-01-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_deny_previous_church'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deny',
            name='previous_church',
        ),
        migrations.AddField(
            model_name='content',
            name='phone',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
