# Generated by Django 5.2.8 on 2026-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_deny_previous_church_content_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='ticket_tier',
            field=models.CharField(blank=True, choices=[('CLASSIC', 'Classic'), ('VIP', 'VIP'), ('PREMIUM', 'Premium')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='classic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='classic_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='has_ticket_tiers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='premium_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='vip_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
