# Generated by Django 5.2.8 on 2026-01-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bookorder_ticket_tier_content_classic_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookorder',
            name='delivery_address_line1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_address_line2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='delivery_recipient_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='bookorder',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
