# Generated by Django 5.2.8 on 2026-01-15 02:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='api.church')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='api.content')),
            ],
            options={
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['church'], name='api_receipt_church__259f6e_idx'), models.Index(fields=['-issued_at'], name='api_receipt_issued__bd1e4b_idx')],
            },
        ),
    ]
