from django.urls import path
from api.views.commissions.commissions_view import add_member_to_commission, church_commissions_summary, create_commission, delete_commission, list_church_commission_members, list_church_commissions, list_church_commissions_with_members, list_commissions, remove_member_from_commission, update_commission, update_member_role_in_commission
from api.views.contents.contents_view import add_comment, add_to_playlist, content_stats_for_church, content_stats_global, create_category, create_content, create_playlist, create_tag, delete_category, delete_comment, delete_content, feed_for_church, get_category, like_content, list_all_playlists, list_categories, list_comments, list_content, list_tags, recommend_for_user, reorder_playlist_item, retrieve_content, trending_content, unlike_content, update_category, update_content, view_content
from .views.auth.auth_views import change_subscription_plan, check_subscription_status, create_subscription, delete_subscription, get_church_subscription, list_all_subscriptions, renew_subscription, send_otp_view, toggle_subscription_status, update_subscription, verify_otp_view
from .views.crud.crud_views import churches_metrics,create_subchurch_view,filter_church_members,get_current_user,update_church_by_owner,delete_church_by_owner,list_owners,list_users,delete_church,update_church,delete_self,update_self,delete_self,list_churches,create_church_view,list_my_churches,verify_church_view,add_church_admin,list_sub_churches

urlpatterns = [
    path("auth/send-otp/", send_otp_view),
    path("auth/verify-otp/", verify_otp_view),
    path("church/create/", create_church_view),
    path("subchurch/create/<int:church_id>/", create_subchurch_view),
    path("church/my/", list_my_churches),
    path("church/verify/<int:church_id>/", verify_church_view),
    path("church/<int:church_id>/admins/add/", add_church_admin),
    path("church/<int:church_id>/sub_churches/", list_sub_churches),
    path("sadmin/users/", list_users),
    path("sadmin/owners/", list_owners),
    path("sadmin/church/<int:church_id>/update/", update_church),
    path("owner/church/<int:church_id>/update/", update_church_by_owner),
    path("sadmin/church/<int:church_id>/delete/", delete_church_by_owner),
    path("owner/church/<int:church_id>/delete/", delete_church),
    path("user/me/update/", update_self),
    path("user/me/delete/", delete_self),
    path("sadmin/churches/", list_churches),
    path("sadmin/churches/metrics", churches_metrics),
    path("user/me/",get_current_user ),
    path("commissions/", list_commissions, name="list_commissions"),
    path("commissions/create/", create_commission, name="create_commission"),
    path("commissions/<int:commission_id>/update/",update_commission, name="update_commission"),
    path("commissions/<int:commission_id>/delete/",delete_commission, name="delete_commission"),
    path("church/<int:church_id>/commissions/",list_church_commissions, name="list_church_commissions"),
    path("church/<int:church_id>/commissions/summary/",church_commissions_summary, name="church_commissions_summary"),
    path("church/<int:church_id>/commissions/<int:commission_id>/members/",list_church_commission_members, name="list_commission_members"),
    path("church/<int:church_id>/commissions/<int:commission_id>/members/add/",add_member_to_commission, name="add_member_to_commission"),
    path("church/<int:church_id>/commissions/<int:commission_id>/members/<int:user_id>/remove/",remove_member_from_commission, name="remove_member_from_commission"),
    path(
    "church/<int:church_id>/commissions/<int:commission_id>/members/<int:user_id>/role/",
    update_member_role_in_commission,
    name="update_member_role_in_commission", 
    ),
    path(
    "church/<int:church_id>/commissions-with-members/",
    list_church_commissions_with_members,
    name="list_church_commissions_with_members"
    ),
    path("church/<int:church_id>/members/", filter_church_members),
    path("categories/", list_categories),
    path("categories/create/", create_category),
    path("categories/<int:category_id>/", get_category),
    path("categories/<int:category_id>/update/", update_category),
    path("categories/<int:category_id>/delete/", delete_category),
    path("contents/", list_content),
    path("contents/<int:content_id>/", retrieve_content),
    path("contents/create/", create_content),
    path("contents/<int:content_id>/update/", update_content),
    path("contents/<int:content_id>/delete/", delete_content),
    path("contents/<int:content_id>/like/", like_content),
    path("contents/<int:content_id>/unlike/", unlike_content),
    path("contents/<int:content_id>/view/", view_content),
    path("contents/<int:content_id>/comments/", list_comments),
    path("contents/<int:content_id>/comments/add/", add_comment),
    path("comments/<int:comment_id>/delete/", delete_comment),
    path("tags/", list_tags),
    path("tags/create/", create_tag),
    path("playlists/create/", create_playlist),
    path("playlists/<int:playlist_id>/add/", add_to_playlist),
    path("playlist-items/<int:item_id>/reorder/", reorder_playlist_item),
    path("playlist/", list_all_playlists, name="playlist-list"),
    path("trending/", trending_content),
    path("recommend/", recommend_for_user),
    path("feed/church/<int:church_id>/", feed_for_church),
    path("stats/contents/", content_stats_global),
    path("stats/contents/church/<int:church_id>/", content_stats_for_church),
    path("subscription/<int:church_id>/", get_church_subscription),
    path("subscription/<int:church_id>/update/", update_subscription),
    path("subscription/<int:church_id>/delete/", delete_subscription),
    path("subscription/<int:church_id>/status/", check_subscription_status),
    path("subscription/<int:church_id>/change-plan/", change_subscription_plan),
    path("subscription/<int:church_id>/toggle/", toggle_subscription_status),
    path("subscription/<int:church_id>/renew/", renew_subscription),
    path("subscriptions/create/", create_subscription),
    path("subscriptions/all/", list_all_subscriptions),
]
# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTE3OTU3LCJpYXQiOjE3NjM1MTMxNTcsImp0aSI6IjQ0OTgyZDY2MWQzNTQxYmQ5YzlmOWY1NmVkZmVjMWE2IiwidXNlcl9pZCI6IjEifQ.eQVbvH6UMV2Ir8Y-AIIwcfetTXz3tngQi60xARO6LpM